### ISSUE TITLE
Potential extra points

### ISSUE THREAD

**Issue by KronsteinerPhilip** [Teaching-HTL-Leonding/console-chart-quiz-KronsteinerPhilip#1]
I have archieved, what is asked for in the console chart to gain extra points. although i have a lot of the sirting algorithm from Markus steininger. thats why i dont know whether i am worthy to gain 2 extrapoints or just one.

**Comment by rstropek** [comment]
Well done, gave you one extra point. No problem if you work in groups on homework. Checking in a ZIP file is the bigger problem for me. Next time, try to check in separate files.
